# 04 Aishawariya Athawale
# 08 Pankti Fadia
# 10 Hetvi Julasana

### Sentiment Analysis Assignment 3

In [1]:
import numpy as np 
import pandas as pd 
import re
import nltk 
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
#The dataset used is: U.S. Airline tweet dataset.

tweets = pd.read_csv("Tweets.csv")
tweets.head()

tweet_id airline_sentiment  airline_sentiment_confidence  \
0  570306133677760513           neutral                        1.0000   
1  570301130888122368          positive                        0.3486   
2  570301083672813571           neutral                        0.6837   
3  570301031407624196          negative                        1.0000   
4  570300817074462722          negative                        1.0000   

  negativereason  negativereason_confidence         airline  \
0            NaN                        NaN  Virgin America   
1            NaN                     0.0000  Virgin America   
2            NaN                        NaN  Virgin America   
3     Bad Flight                     0.7033  Virgin America   
4     Can't Tell                     1.0000  Virgin America   

  airline_sentiment_gold        name negativereason_gold  retweet_count  \
0                    NaN     cairdin                 NaN              0   
1                    NaN    jnardino                 NaN              0   
2                    NaN  yvonnalynn                 NaN              0   
3                    NaN    jnardino                 NaN              0   
4                    NaN    jnardino                 NaN              0   

                                                text tweet_coord  \
0                @VirginAmerica What @dhepburn said.         NaN   
1  @VirginAmerica plus you've added commercials t...         NaN   
2  @VirginAmerica I didn't today... Must mean I n...         NaN   
3  @VirginAmerica it's really aggressive to blast...         NaN   
4  @VirginAmerica and it's a really big bad thing...         NaN   

               tweet_created tweet_location               user_timezone  
0  2015-02-24 11:35:52 -0800            NaN  Eastern Time (US & Canada)  
1  2015-02-24 11:15:59 -0800            NaN  Pacific Time (US & Canada)  
2  2015-02-24 11:15:48 -0800      Lets Play  Central Time (US & Canada)  
3  2015-02-24 11:15:36 -0800            NaN  Pacific Time (US & Canada)  
4  2015-02-24 11:14:45 -0800            NaN  Pacific Time (US & Canada)

In [3]:
features = tweets.iloc[:, 10].values
labels = tweets.iloc[:, 1].values

In [4]:
#In this step we have done some preprocessing on dataset.

new_features = []

for line in range(0, len(features)):
  
    new_feature = re.sub(r'\W', ' ', str(features[line]))
    new_feature= re.sub(r'\s+[a-zA-Z]\s+', ' ', new_feature)
    new_feature = re.sub(r'\^[a-zA-Z]\s+', ' ', new_feature) 

    new_feature = new_feature.lower()

    new_features.append(new_feature)

In [5]:
vectorizer = TfidfVectorizer (max_features=2500, min_df=6, max_df=0.8, stop_words=stopwords.words('english'))
new_features = vectorizer.fit_transform(new_features).toarray()

In [6]:
X_train, X_test, y_train, y_test = train_test_split(new_features, labels, test_size=0.2, random_state=0)

In [7]:
text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)
text_classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=0)

In [8]:
predictions = text_classifier.predict(X_test)

In [9]:
print("confusion matrix:")
print(confusion_matrix(y_test,predictions))
print()
print("Classification Report:")
print(classification_report(y_test,predictions))
print("Accuracy is:",accuracy_score(y_test, predictions))

confusion matrix:
[[1718  107   45]
 [ 335  239   40]
 [ 138   60  246]]

Classification Report:
              precision    recall  f1-score   support

    negative       0.78      0.92      0.85      1870
     neutral       0.59      0.39      0.47       614
    positive       0.74      0.55      0.63       444

    accuracy                           0.75      2928
   macro avg       0.71      0.62      0.65      2928
weighted avg       0.74      0.75      0.73      2928

Accuracy is: 0.7523907103825137
